canteen/urls.py
from django.contrib import admin
from django.urls import path,include
from content import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('content/', include('content.urls')),
    path('', views.home, name='login-page'),
    # path('accounts/', include('content.urls')),
]



from django.conf import settings
from django.conf.urls.static import static


if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

content/urls.py
from django.urls import path
from .import views

app_name="content"


urlpatterns = [
    path('', views.home, name='login-page'),
    path('logout/', views.logout_view, name='logout-page'),
    path('login/', views.home, name='login-page'),
    path('change-password/', views.change_password, name='change-password'),
    path('search-canteen/', views.search_canteen, name='search-canteen'),

    path('store/', views.store, name='store'),
    # path('sandwitch/<int:sandwich_id>/', views.sandwitch, name='sandwitch'),
    path('sandwitch/', views.sandwitch, name='sandwitch'),
    path('add_sandwich_components/<int:type_id>', views.add_sandwich_components, name='add_sandwich_components'),
    path('add_sandwich_component_names/', views.add_sandwich_component_names, name='add_sandwich_component_names'),
    path('sand_current_materials/', views.sand_current_materials, name='sand_current_materials'),

    path('daily_transaction/', views.daily_transaction, name='daily_transaction'),
    path('Treasury_receipt/', views.Treasury_receipt, name='Treasury_receipt'),
    path('receipt_net/', views.receipt_net, name='receipt_net'),
    path('monthly_receipt/', views.monthly_receipt, name='monthly_receipt'),
    path('Debts/', views.Debts, name='Debts'),

    path('add_sandwitch/', views.add_sandwitch, name='add_sandwitch'),
    path('add_new_sandwitch/', views.add_new_sandwitch, name='add_new_sandwitch'),

    path('new_product_type/', views.new_product_type, name='new_product_type'),
    path('add_new_mu/', views.add_new_mu, name='add_new_mu'),
    path('delete_mu/', views.delete_mu, name='delete_mu'),
    path('reduce_product_amount_store/<int:product_id>', views.reduce_product_amount_store, name='reduce_product_amount_store'),
    path('update_product/<int:trader_id>', views.update_product, name='update_product'),
    path('withdrawings_all/', views.withdrawings_all, name='withdrawings_all'),
    path('add_new_sellings/', views.add_new_sellings, name='add_new_sellings'),
    path('trader_page/<int:trader_id>', views.trader_page, name='trader_page'),
    path('add_money_dept/<int:trader_id>', views.add_money_dept, name='add_money_dept'),
    path('restore_trader_product_store/<int:trader_id>', views.restore_trader_product_store, name='restore_trader_product_store'),



    path('product_page/<int:product_id>', views.product_page, name='product_page'),
    path('update_product_prices/<int:product_id>', views.update_product_prices, name='update_product_prices'),
    path('give_payment/<int:trader_id>', views.give_payment, name='give_payment'),
    path('restore_trader_given_bill/<int:trader_id>', views.restore_trader_given_bill, name='restore_trader_given_bill'),
    path('add_trader/<int:status>', views.add_trader, name='add_trader'),


    path('customers-page/', views.customers_page, name='customers-page'),
    path('customer-payment/<int:customer_id>', views.customer_payment, name='customer-payment'),
    path('customer-page/<int:customer_id>', views.customer_page, name='customer-page'),
    path('customer-bill-details/<int:bill_id>', views.customer_bill_details, name='customer-bill-details'),
    path('customers-bill-details-page/', views.customer_bill_details_page, name='customers-bill-details-page'),
    path('restore-customer-bill/<int:customer_id>', views.restore_customer_bill, name='restore-customer-bill'),
    path('confirm-restore-customer-bill/<int:customer_id>', views.confirm_restore_customer_bill, name='confirm-restore-customer-bill'),
    path('restore-customer-bill-line/<int:line_id>', views.restore_customer_bill_line, name='restore-customer-bill-line'),
    path('delete-restored-customer-bill-line/<int:line_id>', views.delete_restored_customer_bill_line, name='delete-restored-customer-bill-line'),
    path('customer_give_payment/<int:customer_id>', views.customer_give_payment, name='customer_give_payment'),
    path('customer_all_unpaid_bills/<int:customer_id>', views.customer_all_unpaid_bills, name='customer_all_unpaid_bills'),

    path('treasury_transactions/', views.treasury_transactions, name='treasury_transactions'),
    path('withdrawings_transactions/', views.withdrawings_transactions, name='withdrawings_transactions'),
    path('delete_single_withdrawing/', views.delete_single_withdrawing, name='delete_single_withdrawing'),


    path('points/', views.points, name='points'),
    path('point_page/<int:point_id>', views.point_page, name='point_page'),
    path('point_trader_page/<int:point_trader_id>', views.point_trader_page, name='point_trader_page'),
    path('add_new_point_bill/<int:product_id>', views.add_new_point_bill, name='add_new_point_bill'),
    path('add_new_point_seller/', views.add_new_point_seller, name='add_new_point_seller'),
    path('add_new_point_payments/<int:point_id>', views.add_new_point_payments, name='add_new_point_payments'),
    path('add_new_point_sellings/<int:point_id>', views.add_new_point_sellings, name='add_new_point_sellings'),
    path('restore_point_bill_sell/<int:bill_id>', views.restore_point_bill_sell, name='restore_point_bill_sell'),
    path('restore_point_product_store/<int:point_id>', views.restore_point_product_store, name='restore_point_product_store'),
    path('point_to_point_product/<int:point_id>', views.point_to_point_product, name='point_to_point_product'),
    path('point-total-product/<int:tpp>', views.point_total_product, name='point-total-product'),
    path('all-discount-bills/', views.all_discount_bills, name='all-discount-bills'),


    path('manager/<int:manager_id>', views.manager, name='manager'),
    path('daily_reports', views.daily_reports, name='daily_reports'),
    path('denied/', views.denied, name='denied_page'),
    # path('all_types/', views.all_types, name='all_types'),
]

content/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.models import User
from .models import Sandwich, DaySandwich, Product, Day_Payment_Line, Acumulate_payment, Safe_data, withdrawings,Current_manager,Trader, Trader_Product, Trader_Payment
from .models import Point, Point_User, Point_Product, Point_User_Payment, Safe_Month,Point_Product_Sellings,Total_Point_Product,Month_Total_Calculation
from .models import Trader_Product_Data, Customer, Customer_Bill
from datetime import datetime,date
# from django.db.models import Q
from django.utils import timezone
import decimal
from django.db.models import Sum,Q
# Create your views here.
from .sandwich_views import add_sandwich_components,add_new_sandwitch ,sandwitch,add_sandwitch,add_sandwich_component_names, sand_current_materials, sand_all_buy
from .trader_views import Debts, trader_page,add_trader,give_payment,restore_trader_product_store, add_money_dept, restore_trader_given_bill
from .points_views import points , point_page, point_trader_page, add_new_point_bill , add_new_point_sellings,add_new_point_payments, add_new_point_seller
from .points_views import  restore_point_bill_sell, restore_point_product_store, point_to_point_product, point_total_product, all_discount_bills,get_all_bills_with_discount

from .daily_views import daily_reports,daily_transaction
from .product_views import product_page, update_product, update_product_prices,new_product_type, reduce_product_amount_store, add_new_mu, delete_mu
from .customers_views import customers_page ,customer_page,customer_payment, customer_bill_details, restore_customer_bill,restore_customer_bill_line, confirm_restore_customer_bill
from .customers_views import delete_restored_customer_bill_line,customer_give_payment, customer_all_unpaid_bills, customer_bill_details_page

def home(request):
    failed = 0

    if request.method == 'POST':

        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None :
            current_manager = Current_manager.objects.filter(user = user).first()
            if current_manager != None  and current_manager.active_status == 1:
                request.session.set_expiry(0)
                failed =0
                login(request, user)
                print('username: ' + request.user.username + ' has log in to system at ' + str(datetime.now()))
                return redirect("content:receipt_net")
            else :
                failed =1
        else:
            failed =1
    context = {'failed' : failed}
    return render(request, 'content/login.html', context = context)
    return render(request, 'content/login.html')

@login_required
def logout_view(request):

    if request.user != None:
            userna = request.user.username
            logout(request)
            print('username: ' + userna + ' has log out of system at ' + str(datetime.now()))

    return redirect('content:login-page')


@login_required
def manager(request,manager_id):

        context = {

        }
        return render(request, 'content/manager.html',context = context)


@login_required
def store(request):

        products = Product.objects.all()

        total = 0
        if products != None :
            total = sum(p.total_cost for p in products)
        context = {
            'products':products,
            'total':round(total,1),
        }
        # print( len(products))

        return render(request, 'content/store.html',context = context)




@login_required
def Treasury_receipt(request):
    current_manager = Current_manager.objects.filter(user = request.user).first()
    transactions = Safe_data.objects.filter(day__date__gte = current_manager.start_date , day__date__lte=  current_manager.end_date).order_by('-id')
    m_safe = Safe_Month.objects.last()
    context = {
        'transactions':transactions,
        'safe':m_safe,
    }
    return render(request, 'content/Treasury_receipt.html',context)

@login_required
def receipt_net(request):
    sand_buy = sand_all_buy()
    mtc = Month_Total_Calculation.objects.last()
    # next_manager_gmoney = mtc.traders_depts - (mtc.total_products_money + mtc.total_products_money_points +sand_buy )
    # next_manager_gmoney = round(next_manager_gmoney , 0)
    total_money_with_customers_d = mtc.total_products_money_points + mtc.total_products_money + sand_buy+mtc.customers_depts +mtc.safe_current_money
    total_money_with_customers_d = round(total_money_with_customers_d , 1)
    total_net = total_money_with_customers_d - mtc.traders_depts

    given_boss_gmoney = round(total_net - mtc.customers_depts   , 1 )

    ### totalt profit = total_net + total_withdrawings
    total_profit = total_net  + mtc.total_withdrawings
    three_percentage = round((total_profit) *.03 , 0)
    one_percentage = round((total_profit) *.01 , 0)
    cur_m = Current_manager.objects.get(user = request.user)


    bills_with_discount = get_all_bills_with_discount(request)

    total_discounts = sum(b.total_discount for b in bills_with_discount )

    context={
        'mtc':mtc,
        'sand_st':sand_buy,
        # 'next_manager_gmoney':next_manager_gmoney,
        'given_boss_gmoney':given_boss_gmoney,
        'three_percentage':three_percentage,
        'one_percentage':one_percentage,
        'total_discounts':total_discounts,
        'total_money_with_customers_d':total_money_with_customers_d,
        'total_net':total_net,

    }
    return render(request, 'content/receipt_net.html', context)

@login_required
def monthly_receipt(request):
    today_date = timezone.now().date()
    manager = Current_manager.objects.filter(user = request.user ).first()
    mtc = Month_Total_Calculation.objects.filter(current_manager = manager).last()

    context = {
        'mtc':mtc,
    }
    return render(request, 'content/monthly_receipt.html',context)


@login_required
def withdrawings_all(request):
    current_manager = Current_manager.objects.filter(user = request.user).first()
    transactions = withdrawings.objects.filter(day__date__gte = current_manager.start_date , day__date__lte=  current_manager.end_date).order_by('-id')
    total_tr_money = 0

    for t in transactions:
        total_tr_money += t.money_amount
    context = {
        'transactions':transactions,
        'total_tr_money':total_tr_money,
    }
    return render(request, 'content/withdrawings.html',context)




@login_required
@user_passes_test(lambda u: u.groups.filter(name='managers').count() != 0, login_url='content:denied_page')
def treasury_transactions(request):
    success = failed =0

    if request.method == "POST":
        # date = request.POST['date']
        date = timezone.now()
        amount = float(request.POST['amount'])
        manager = Current_manager.objects.get(user = request.user)
        notes = request.POST['notes']
        ## get current manager safe
        m_safe = Safe_Month.objects.last()
        mtc = Month_Total_Calculation.objects.last()
        ## test amount against trader remaining_money
        if amount < 0:
            if  m_safe.money >= abs(amount)  :
                m_safe.money -= abs(amount)
                m_safe.save()
                mtc.safe_current_money = m_safe.money
                mtc.save()
                Safe_data.objects.create(day = date, money_amount = amount, given_person =manager, notes=notes ,safe_line_status = 6 )
                success = 1
            else:
                failed = 1

        elif amount > 0 : ## positive amount
            m_safe.money += amount
            m_safe.save()
            mtc.safe_current_money = m_safe.money
            mtc.save()
            Safe_data.objects.create(day = date, money_amount = amount, given_person =manager, notes=notes )
            success = 1



    today_date =  timezone.now().date()
    # managers = Current_manager.objects.filter(end_date__gte = today_date )
    # traders = Trader.objects.all()
    context = {
            'success':success,
            'failed':failed,
            # 'managers':managers,

    }
    return render(request, 'content/treasury_transactions.html',context)







@login_required
@user_passes_test(lambda u: u.groups.filter(name='managers').count() != 0, login_url='content:denied_page')
def withdrawings_transactions(request):
    success = failed =0

    if request.method == "POST":
        # date = request.POST['date']
        date = timezone.now()
        amount = float(request.POST['amount'])
        notes = request.POST['notes']
        ## get current manager safe
        m_safe = Safe_Month.objects.last()
        ## test amount against trader remaining_money
        manager = Current_manager.objects.filter(user = request.user).first()
        mtc = Month_Total_Calculation.objects.last()
        if m_safe.money >= abs(amount)  :
            withdrawings.objects.create(day = date, money_amount = amount, descreption=notes , status = 2 )
            Safe_data.objects.create(day = date, money_amount = -amount, given_person =manager, notes=notes , safe_line_status = 1 )

            m_safe.money -= abs(amount)
            m_safe.save()
            ## update mtc
            mtc.total_withdrawings += abs(amount)
            mtc.safe_current_money -= abs(amount)
            mtc.save()
            success = 1
        else:
            failed = 1



    context = {
            'success':success,
            'failed':failed,


    }
    return render(request, 'content/withdrawings_transactions.html', context)






@login_required
@user_passes_test(lambda u: u.groups.filter(name='managers').count() != 0, login_url='content:denied_page')
def add_new_sellings(request):
    failed = success =total_comings=  0

    if request.method == 'POST':
        sell_amount = int(request.POST['quantity'])

content/templates/content/denied.html
{% extends './base.html' %}
{% block content %}

<div >
  <div class="text-danger text-center font-weight-bold p-3  mb-4  container jumbotron">
          <h1> عفوا لا تمتلك صلاحيات الوصول لهذا المحتوى  )):</h1>
  </div>
</div>





{%endblock%}

content/templates/content/point_page.html
{% extends './base.html' %}
{% block content %}

<div class="select-date text-center font-weight-bold p-3 mb-4">
  <div class="bg-light p-2 rounded">
    {{point.name}}
  </div>
</div>

<div>
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item">النقاط</li>
      <li class="breadcrumb-item">{{point.name}}</li>
    </ol>
  </nav>
</div>

<div class="form-group row">
  <label for="inputPassword" class="col-sm-3 font-weight-bold col-form-label">اجمالي البضاعة الموجودة</label>
  <div class="col-sm-9">
  <div class="input-group mb-3">
      <span  class="form-control text-right" id="price-for-unit" aria-label="Amount (to the nearest dollar)">{{all_products_count}}   صنف</span>
  </div>
  </div>
</div>


<!-- start seperator -->
<div style="border-top: 7px solid #1abc9c;" class="my-5"></div>
<!-- end seperator -->

<div class="row font-weight-bold justify-content-around mt-5">
  <p>مبيعات النقطة عن يوم : <span class="today-date"></span></p>
    {%if user.groups.first.name == "managers"%}
  <a href="{%url 'content:add_new_point_sellings' point.id%}">
    <button class="btn btn-hover font-weight-bold px-2">تسجيل  مبيعات النقطة</button>
  </a>

    <a href="{%url 'content:add_new_point_payments' point.id%}">
          <button class="btn btn-hover font-weight-bold px-2">تسجيل مدفوعات نقطة</button>
    </a>
    <!-- <a href="{%url 'content:add_new_point_payments' point.id%}">
          <button class="btn btn-hover font-weight-bold px-2">تسجيل فاتورة عميل</button>
    </a> -->
    <div class="">
      <a href="{%url 'content:points'  %}">
          <button class="btn y btn-hover font-weight-bold px-5 mx-2">رجوع</button>
      </a>
      </div>
    {%endif%}
</div>
<table class="table">
    <thead class="thead-dark">
      <tr>
        <th scope="col">#</th>
        <th scope="col">الصنف</th>
        <th scope="col">ك.ق</th>
        <th scope="col">ق.ق</th>
        <th scope="col">ك.ج</th>
        <th scope="col">ق.ج</th>
        <th scope="col">سعر البيع</th>
        <th scope="col">الخصم للقطعة</th>
        <th scope="col">الخصم الكلى</th>

        <th scope="col">الاجمالي</th>
        <th scope="col">المطلوب</th>
        <th scope="col" class="text-danger"> نسبة الخصم</th>

        <th scope="col" class="text-danger">الكمية المسترجعة</th>
        <th scope="col" class="text-danger">الكمية المباعة</th>
        <th scope="col">تاريخ الفاتورة</th>

      </tr>
    </thead>
    <tbody>
      {% for bill in bills %}
      <tr>
        <th scope="row">{{forloop.counter}}</th>

        <td>{{bill.product.name}}</td>
        <td>{{bill.quantity_packet_old}}</td>
        <td>{{bill.quantity_old}}</td>
        <td>{{bill.quantity_packet_new}}</td>
        <td>{{bill.quantity_new}}</td>
        <td>{{bill.product.unit_sell_price}}</td>
        <td>{{bill.discount_per_unit}}</td>
        <td>{{bill.total_discount}}</td>
        <td>{{bill.money_quantity_sell}}</td>
        <td>{{bill.required_amount}}</td>
        <th class="text-danger">{% widthratio bill.total_discount  bill.money_quantity_sell  100 %}%</th>


        <td>{{bill.restored_amount}}</td>
        <td>{{bill.total_quantity_sold}}</td>

        <td>{{bill.date}}</td>

      </tr>
      {% endfor %}

    </tbody>
</table>
<hr class="my-5">
<div class="container mt-5">
  <div class='row text-center'>
    <div class="col-4 bg-dark text-light font-weight-bolder p-3">الاجمالي</div>
    <div class="col-8 font-weight-bolder  p-3">{{total_sellings}}</div>
  </div>

</div>

<!-- start seperator -->
<div style="border-top: 7px solid #1abc9c;" class="my-5"></div>
<!-- end seperator -->

<div class="row text-danger font-weight-bold justify-content-around mt-5">
  <p>فواتير مسترجعة اليوم  <span class="today-date"></span></p>
</div>
<table class="table">
    <thead class="thead-dark">
      <tr>
        <th scope="col">#</th>
        <th scope="col">الصنف</th>
        <th scope="col">ك.ق</th>
        <th scope="col">ق.ق</th>
        <th scope="col">ك.ج</th>
        <th scope="col">ق.ج</th>
        <th scope="col">سعر البيع</th>
        <th scope="col">الخصم للقطعة</th>
        <th scope="col">الخصم الكلى</th>

        <th scope="col">الاجمالي</th>
        <th scope="col text-danger">قيمة المسترجع</th>

        <th scope="col" class="text-danger">الكمية المسترجعة</th>
        <th scope="col" class="text-danger">الكمية المباعة</th>
        <th scope="col">تاريخ الفاتورة</th>

      </tr>
    </thead>
    <tbody>
      {% for bill in restored_bills %}
      <tr>
        <th scope="row">{{forloop.counter}}</th>

        <td>{{bill.product.name}}</td>
        <td>{{bill.quantity_packet_old}}</td>
        <td>{{bill.quantity_old}}</td>
        <td>{{bill.quantity_packet_new}}</td>
        <td>{{bill.quantity_new}}</td>
        <td>{{bill.product.unit_sell_price}}</td>
        <td>{{bill.discount_per_unit}}</td>
        <td>{{bill.total_discount}}</td>
        <td>{{bill.money_quantity_sell}}</td>
        <td>{{bill.required_amount}}</td>


        <td>{{bill.restored_amount}}</td>
        <td>{{bill.restored_amount_cost_ad}}</td>

        <td>{{bill.date}}</td>

      </tr>
      {% endfor %}

    </tbody>
</table>
<hr class="my-5">
<div class="container mt-5">
  <div class='row text-center'>
    <div class="col-3 bg-dark text-light font-weight-bolder p-3">الاجمالي بيع بعد الخصم</div>
    <div class="col-3 font-weight-bolder  p-3">{{restored_total_bills_sell}}</div>
    <div class="col-3 bg-dark text-light font-weight-bolder p-3">الاجمالي شراء</div>
    <div class="col-3 font-weight-bolder  p-3">{{restored_total_bills_buy}}</div>
  </div>

<!-- start seperator -->

<!-- start section seperator -->
<div>
  <div class="select-date text-center font-weight-bold p-3 mb-4" style="position: relative;
  top: 60px;">
      <div class="bg-light p-2 rounded">
        <p>البضائع المسحوبة عن يوم : <span class="today-date"></span></p>
      </div>
  </div>

  <div style="border-top: 7px solid #1abc9c;"></div>

  <form method="post">
    {%csrf_token%}
    <div class="container select-date-big text-center font-weight-bold p-3 mb-4">
      <div class="input-group ">
        <div class="input-group-prepend">
          <span class="input-group-text font-weight-bold rounded-0" id="inputGroup-sizing-sm"> من تاريخ </span>
        </div>
        <input type="date" name="from_date" class="form-control rounded-0" aria-label="Sizing example input"
          aria-describedby="inputGroup-sizing-sm" required>


        <div class="input-group-prepend mr-2">
          <span class="input-group-text font-weight-bold rounded-0" id="inputGroup-sizing-sm">الى تاريخ</span>
        </div>
        <input type="date" name="to_date" class="form-control rounded-0" aria-label="Sizing example input"
          aria-describedby="inputGroup-sizing-sm" required>

        <button class="d-none" type="submit"></button>
      </div>
    </div>
  </form>
</div>
<!-- end section seperator -->
<!-- end seperator -->
<table class="table">
    <thead class="thead-dark">
      <tr>
        <th scope="col">#</th>
        <th scope="col">الصنف</th>
        <th scope="col">ك.ق</th>
        <th scope="col">ق.ق</th>
        <th scope="col">ك.ج</th>
        <th scope="col">ق.ج</th>

        <th scope="col">الاجمالي</th>
        <th scope="col">تاريخ الفاتورة</th>
        <th scope="col">ملاحظات</th>
       <!--  <th scope="col">حالة الفاتورة</th> -->

      </tr>
    </thead>
    <tbody>
      {% for bill in today_point_products %}
      <tr>
        <th scope="row">{{forloop.counter}}</th>

        <td>{{bill.product.name}}</td>
        <td>{{bill.quantity_packet_old}}</td>
        <td>{{bill.quantity_old}}</td>
        <td>{{bill.quantity_packet_new}}</td>
        <td>{{bill.quantity_new}}</td>
        <td>{{bill.money_quantity}}</td>
        <td>{{bill.date}}</td>
        <td>{{bill.notes}}</td>
      <!--  {%if bill.given_status == 1%}
          <td class="text-primary">تم التسليم</td>
        {%else%}
          <td class="text-danger">لم يتم التسليم</td>
        {%endif%} -->
      </tr>
      {% endfor %}

    </tbody>
</table>
<hr class="my-5">
<div class="container mt-5">
  <div class='row text-center'>
    <div class="col-4 bg-dark text-light font-weight-bolder p-3">الاجمالي</div>
    <div class="col-8 font-weight-bolder  p-3">{{today_dept}}</div>
  </div>

</div>


<!-- start section seperator -->
<div>
  <div class="select-date text-center font-weight-bold p-3 mb-4" style="position: relative;
  top: 60px;">
      <div class="bg-light p-2 rounded">
        البضائع الموجودة بالنقطة حتى الآن
      </div>


  </div>

  <div style="border-top: 7px solid #1abc9c;"></div>
</div>
<!-- end section seperator -->
<div class="mt-5">
  {%if user.groups.first.name == "managers"%}
    <a href="{%url 'content:restore_point_product_store' point.id%}">
      <button class="btn btn-danger font-weight-bold px-5">استرجاع بضاعة للمخزن</button>
    </a>
    <a href="{%url 'content:point_to_point_product' point.id%}">
      <button class="btn btn-warning font-weight-bold px-5">نقل بضاعة من نقطة لاخرى</button>
    </a>

  {%endif%}
</div>
<table class="table">
    <thead class="thead-dark">
      <tr>
        <th scope="col">#</th>
        <th scope="col">الصنف</th>
        <th scope="col">الكمية بالقطعة</th>
        <th scope="col">سعر الشراء</th>
        <th scope="col">تفاصيل الصنف بالنقطة</th>
      </tr>
    </thead>
    <tbody>
      {% for p in all_products %}
        {%if p.total_product_quantity == 0%}
          <tr class="text-danger font-weight-bold">
        {%else%}
          <tr>
        {%endif%}
          <th scope="row">{{forloop.counter}}</th>

          <td>{{p.product.name}}</td>
          <td>{{p.total_product_quantity}}</td>
          <td>{{p.total_cost}}</td>
          <td> <a href="{% url 'content:point-total-product' p.id %}"> اضغط لرؤية تفاصيل الصنف  </a></td>
        </tr>
      {% endfor %}

    </tbody>
</table>
<hr class="my-5">
<div class="container mt-5">
  <div class='row text-center'>
    <div class="col-4 bg-dark text-light font-weight-bolder p-3">الاجمالي</div>
    <div class="col-8 font-weight-bolder  p-3">{{total_dept}}</div>
  </div>

</div>


<!-- start section seperator -->
<div>
  <div class="select-date text-center font-weight-bold p-3 mb-4" style="position: relative;
  top: 60px;">
      <div class="bg-light p-2 rounded">
        فواتير النقطة حتى الآن
      </div>
  </div>

  <div style="border-top: 7px solid #1abc9c;"></div>
</div>
<!-- end section seperator -->

<table class="table">
    <thead class="thead-dark">
      <tr>
        <th scope="col">#</th>
        <th scope="col">المبلغ</th>
        <th scope="col">المستلم</th>
        <th scope="col">التاريخ</th>

      </tr>
    </thead>
    <tbody>
      {% for bill in all_bills %}
      <tr>
        <th scope="row">{{forloop.counter}}</th>
        <td>{{bill.amount}}</td>
        <td>{{bill.t_user}}</td>
        <td>{{bill.date}}</td>
      </tr>
      {% endfor %}

    </tbody>
</table>
<hr class="my-5">
<div class="container mt-5">
  <div class='row text-center'>
    <div class="col-4 bg-dark text-light font-weight-bolder p-3">الاجمالي</div>
    <div class="col-8 font-weight-bolder  p-3">{{bills_amount}}</div>
  </div>

</div>

    {% if failed == 1 %}
    <div class="alert alert-danger text-center mt-3 mb-0" role="alert">
      خطأ لم يتم تحديث البيانات . تأكد من اسم المنتج و الكمية الصحيحة
    </div>
    {%elif success %}
    <div class="alert alert-success text-center mt-3 mb-0" role="alert">
      تم حفظ البيانات
    </div>
    {% endif %}

    <script>
      const navLinks = document.querySelectorAll(".nav-item")
      for (link of navLinks){
          link.classList.remove('active-link')
      }
      navLinks[7].classList.add('active-link');

    </script>


{%endblock%}